// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub primarypool_factory_pool_createds: ::prost::alloc::vec::Vec<PrimarypoolFactoryPoolCreated>,
    #[prost(message, repeated, tag="2")]
    pub primary_pool_subscriptions: ::prost::alloc::vec::Vec<PrimaryPoolSubscription>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimarypoolFactoryPoolCreated {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimaryPoolSubscription {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(string, tag="5")]
    pub evt_address: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub asset_in: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub asset_out: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub subscription: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="9")]
    pub investor: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="10")]
    pub price: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub execution_date: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimaryPoolSubscriptions {
    #[prost(string, tag="1")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub items: ::prost::alloc::vec::Vec<PrimaryPoolSubscription>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrimaryPoolSubscriptionsList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<PrimaryPoolSubscriptions>,
}
// @@protoc_insertion_point(module)
