// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub marginpool_factory_pool_createds: ::prost::alloc::vec::Vec<MarginpoolFactoryPoolCreated>,
    #[prost(message, repeated, tag="2")]
    pub margin_pool_margin_trade_reports: ::prost::alloc::vec::Vec<MarginPoolMarginTradeReport>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginpoolFactoryPoolCreated {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(bytes="vec", tag="5")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginPoolMarginTradeReport {
    #[prost(string, tag="1")]
    pub evt_tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="2")]
    pub evt_index: u32,
    #[prost(message, optional, tag="3")]
    pub evt_block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="4")]
    pub evt_block_number: u64,
    #[prost(string, tag="5")]
    pub evt_address: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub security: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="7")]
    pub order_ref: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub party: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub counterparty: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="10")]
    pub order_type: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub price: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="12")]
    pub currency: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="13")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub execution_date: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginPoolTradeReports {
    #[prost(string, tag="1")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub items: ::prost::alloc::vec::Vec<MarginPoolMarginTradeReport>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginPoolTradeReportsList {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<MarginPoolTradeReports>,
}
// @@protoc_insertion_point(module)
